<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['nat_firewall_add_nat_rule'] = 'Добавьте 1:1 правило NAT';
$lang['nat_firewall_app_description'] = '1:1 NAT отображает общедоступный IP-адрес через частный IP-адрес, предоставляющий доступ к системе за брандмауэром через общедоступный IP адрес.';
$lang['nat_firewall_app_name'] = '1:1 NAT';
$lang['nat_firewall_lan_ip'] = 'LAN IP';
$lang['nat_firewall_no_external_nic'] = '1:1 NAT требует по крайней мере одного внешнего настроенного сетевого интерфейса.';
$lang['nat_firewall_port_or_port_range'] = 'Порт или диапазон портов';
$lang['nat_firewall_private_ip'] = 'Частный IP';
$lang['nat_firewall_public_ip'] = 'Общедоступный IP';
$lang['nat_firewall_rules'] = '1:1 правила NAT';
$lang['nat_firewall_tooltip'] = 'Эта функция требует дополнительных общедоступных IP-адресов от вашего Интернет-провайдера (ISP).';
$lang['nat_firewall_wan_ip'] = 'WAN IP';
