<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['nat_firewall_add_nat_rule'] = 'Dodaj regułę NAT 1-do-1';
$lang['nat_firewall_app_description'] = 'NAT 1-do-1 mapuje publiczny adres IP do prywatnego adresu IP umożliwiając dostęp do systemów za firewallem poprzez publiczny adres IP.';
$lang['nat_firewall_app_name'] = 'NAT 1-do-1';
$lang['nat_firewall_lan_ip'] = 'LAN IP';
$lang['nat_firewall_no_external_nic'] = 'NAT 1-do-1 wymaga przynajmniej jednego interfejsu sieciowego ustawionego jako interfejs zewnętrzny.';
$lang['nat_firewall_port_or_port_range'] = 'Port lub zakres portów';
$lang['nat_firewall_private_ip'] = 'Prywatny adres IP';
$lang['nat_firewall_public_ip'] = 'Publiczny adres IP';
$lang['nat_firewall_rules'] = 'Reguły NAT 1-do-1';
$lang['nat_firewall_tooltip'] = 'Ta funkcja wymaga dodatkowych publicznych adresów IP od Twojego dostawcy internetu (ISP).';
$lang['nat_firewall_wan_ip'] = 'WAN IP';
