<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['nat_firewall_add_nat_rule'] = 'Dodaj regułę NAT 1-do-1';
$lang['nat_firewall_app_description'] = 'The 1-to-1 NAT Firewall app maps a public IP address to a private IP address allowing access to systems behind the firewall via a public IP address.';
$lang['nat_firewall_app_name'] = '1-to-1 NAT Firewall';
$lang['nat_firewall_lan_ip'] = 'Lokalny adres IP';
$lang['nat_firewall_no_external_nic'] = 'NAT 1-do-1 wymaga przynajmniej jednego interfejsu sieciowego ustawionego jako interfejs zewnętrzny.';
$lang['nat_firewall_port_or_port_range'] = 'Port lub zakres portów';
$lang['nat_firewall_private_ip'] = 'Prywatny adres IP';
$lang['nat_firewall_public_ip'] = 'Publiczny adres IP';
$lang['nat_firewall_rules'] = 'Reguły NAT 1-do-1';
$lang['nat_firewall_tooltip'] = 'Ta funkcja wymaga dodatkowych publicznych adresów IP od Twojego dostawcy internetu (ISP).';
$lang['nat_firewall_wan_ip'] = 'Zewnętrzny adres IP';
